# Generated by Django 5.2 on 2025-05-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_usuariopersonalizado_amigos_solicitudamistad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('GASTO', 'Nuevo Gasto'), ('ACTIVIDAD', 'Nueva Actividad'), ('COMENTARIO', 'Nuevo Comentario'), ('COLABORADOR', 'Nuevo Colaborador'), ('PAGO', 'Recordatorio de Pago'), ('SOLICITUD_AMISTAD', 'Solicitud de Amistad'), ('SOLICITUD_ACEPTADA', 'Solicitud Aceptada'), ('OTROS', 'Otros')], default='OTROS', max_length=20),
        ),
    ]
