# Generated by Django 5.2.1 on 2025-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='categoria',
            field=models.CharField(blank=True, choices=[('PLAYA', 'Playa'), ('CIUDAD', 'Ciudad'), ('MONTAÑA', 'Montaña'), ('RURAL', 'Rural'), ('CULTURAL', 'Cultural')], default='CIUDAD', max_length=20, null=True),
        ),
    ]
