# Generated by Django 5.2.1 on 2025-05-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_viaje_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='visibilidad',
            field=models.CharField(choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Público')], default='PRIVADO', max_length=20),
        ),
    ]
