# Generated by Django 5.2.1 on 2025-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_alter_viaje_visibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='viaje/'),
        ),
    ]
