# Generated by Django 5.2.1 on 2025-06-01 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_viaje_imagen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='megusta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='megusta',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_gustas_viaje', to='viajes.viaje'),
        ),
        migrations.AlterField(
            model_name='megusta',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_gustas', to='viajes.actividad'),
        ),
        migrations.AddConstraint(
            model_name='megusta',
            constraint=models.UniqueConstraint(condition=models.Q(('actividad__isnull', False)), fields=('usuario', 'actividad'), name='unique_like_actividad'),
        ),
        migrations.AddConstraint(
            model_name='megusta',
            constraint=models.UniqueConstraint(condition=models.Q(('viaje__isnull', False)), fields=('usuario', 'viaje'), name='unique_like_viaje'),
        ),
    ]
